# Generated by Django 5.0.7 on 2024-12-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_savepost'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavePost',
            new_name='SavedPost',
        ),
    ]
