# Generated by Django 5.0.7 on 2024-08-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImg',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileImg',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
